import type { ReactNode } from 'react'
import type { Metadata } from 'next'
import { Open_Sans } from 'next/font/google'

import { DashboardWrapper } from '@/components/dashboardWrapper'

import './globals.css'

const openSans = Open_Sans({
  variable: '--font-open-sans',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode
}>) {
  return (
    <html
      lang='en'
      className={`${openSans.variable} h-full antialiased`}>
      <body>
        <DashboardWrapper>{children}</DashboardWrapper>
      </body>
    </html>
  )
}
