import type { ReactNode } from 'react'
import type { Metadata } from 'next'
import { Open_Sans } from 'next/font/google'

import { DashBoardLayout } from '@/components/dashboard/dashBoardLayout'
import StoreProvider from '@/state/store'
import { MuiThemeProvider } from '@/providers/MuiThemeProvider'

import './globals.css'

const openSans = Open_Sans({
  variable: '--font-open-sans',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode
}>) {
  return (
    <html
      lang='en'
      className={`${openSans.variable} h-full antialiased`}>
      <body>
        <StoreProvider>
          <MuiThemeProvider>
            <DashBoardLayout>{children}</DashBoardLayout>
          </MuiThemeProvider>
        </StoreProvider>
      </body>
    </html>
  )
}
